### ISSUE TITLE
[如何指定我要下载的镜像架构] 

### ISSUE THREAD

**Issue by NullPointerExcp** [kubesre/docker-registry-mirrors#1152]
**描述问题**
我的电脑是amd64架构，我需要下载arm64架构的镜像
  
  
**截图**
  
  
**额外的日志信息**
在这里添加有关该问题的其他描述。

@gebangfeng

**Comment by gebangfeng** [comment]
你是没法运行的，也没法拉到你本地

**Comment by NullPointerExcp** [comment]
> 你是没法运行的，也没法拉到你本地

我是想拉到本地虚拟机中，然后上传到服务器，服务器是离线环境ARM架构的

**Comment by gebangfeng** [comment]
skopeo 貌似能把镜像导出成tar包。你可以研究研究

**Comment by gebangfeng** [comment]
参考命令：docker run -it --rm swr.cn-east-3.myhuaweicloud.com/kubesre/quay.io/skopeo/stable:latest copy --multi-arch system  docker://quay.io/skopeo/stable:latest oci://1.tar.gz

**Comment by gebangfeng** [comment]
![9d437e5209f0bc26bef3bc63707106f](https://github.com/user-attachments/assets/269df017-684c-4dc9-b56a-98ffc2e82ae9)
查了下docker文档，docker本身就支持的
 docker pull --platform arm64 nginx
[root@VM-12-4-centos proxy-gateway]# cat /etc/docker/daemon.json 
{
"experimental": true,
    "registry-mirrors": [
        "https://mirror.ccs.tencentyun.com"
    ]
}
