### ISSUE TITLE
Repeat

### ISSUE THREAD

**Issue by xaw330** [kubesre/docker-registry-mirrors#3]
<img width="301" alt="0dac6b8846eaa8a95d2cdf6dbf3db22" src="https://github.com/kubesre/docker-registry-mirrors/assets/145673991/6fe19b3a-fc8b-4c9e-8841-17f710550211">

Repeat!!!

**Comment by gebangfeng** [comment]
Thanks for pointing out

**Comment by 16675581724** [comment]
是不是都被禁用了，我ping都ping不到了

**Comment by ye7love7** [comment]
sudo docker pull docker.kubesre.xyz/xprobe/xinference:v0.12.0 成功
