### ISSUE TITLE
可以简单的说一下实现的原理吗？感谢

### ISSUE THREAD

**Issue by zxitedu** [kubesre/docker-registry-mirrors#6]
我理解的是服务器是代理的作用，然后使用Nginx做了转发，不知道对不对，还有就是不太理解这里的网关的作用是什么，还有docker部署的两个crproxy 和 nginx-certbot的作用是什么？如果可以的话 希望可以简单的说一下了 感谢🙏

**Comment by gebangfeng** [comment]
`crproxy` 是一个多源仓库聚合代理，通过它可以实现增加前缀方式拉取多个仓库的镜像。其实现原理也是反向代理，例如：`crproxy:8080/docker.io/nginx:latest` 拉取dockerhub里的镜像和 `crproxy:8080/gcr.io/nginx:latest`拉取谷歌仓库的镜像。详细信息可以参考 [crproxy](https://github.com/wzshiming/crproxy/tree/master) 的仓库。

`nginx-certbot` 是一个内置了 `certbot` 的 Nginx，方便申请 SSL 证书。称它为网关是因为它是服务访问的入口。在这个项目中，网关和别名的概念通过网关可以拉取镜像时增加前缀，例如：`kubesre.xyz/docker.io/nginx:latest`。这样可以通过别名简化操作，例如别名 `docker.kubesre.xyz` 可以拉取 Docker Hub 的镜像。当通过这个别名拉取镜像时时，通过 Nginx 将 `docker.kubesre.xyz/nginx` 重定向到 `kubesre.xyz/docker.io/nginx`。
