### ISSUE TITLE
用render拉取镜像直接找不到 

### ISSUE THREAD

**Issue by Glendia** [kubesre/docker-registry-mirrors#772]
docker镜像中心能搜索到镜像，但是render拉取的时候显示找不到怎么解决

**Comment by gebangfeng** [comment]
你是怎么拉取的呢

**Comment by gebangfeng** [comment]
提供一下拉取命令和报错

**Comment by Glendia** [comment]
> 提供一下拉取命令和报错

按照教程，new-web service-docker-docker images:gebangfeng/dockerproxy:0.7
![IMG_20240709_152100](https://github.com/kubesre/docker-registry-mirrors/assets/49245772/0ed3390b-5eca-4dde-970b-e4394495f0da)  
错误提示:No public image found. It looks like you may be using a private image - please add a credential or check the image URL for mistakes.
找不到公共映像。看起来你可能在使用私人图像-请添加凭据或检查图像URL是否有错误。

**Comment by Glendia** [comment]
> > 提供一下拉取命令和报错
> 
> 按照教程，new-web service-docker-docker images:gebangfeng/dockerproxy:0.7 ![IMG_20240709_152100](https://private-user-images.githubusercontent.com/49245772/346856819-0ed3390b-5eca-4dde-970b-e4394495f0da.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTAwNzcsIm5iZiI6MTcyMDUwOTc3NywicGF0aCI6Ii80OTI0NTc3Mi8zNDY4NTY4MTktMGVkMzM5MGItNWVjYS00ZGRlLTk3MGItZTQzOTQ0OTVmMGRhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA3MjI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMjdiMTcyNTU0NjQxN2RmNDBkNGNlZDc3MzM0YzlkNTgwMGMxZTVjNmI5ZmMyNmRkZDk3OTVmYjk2MDM3N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sfU88UswP8_HvCovHtbvDWRbxYkz0pmt1DPyj9Qm1J4) 错误提示:No public image found. It looks like you may be using a private image - please add a credential or check the image URL for mistakes. 找不到公共映像。看起来你可能在使用私人图像-请添加凭据或检查图像URL是否有错误。

是不是你的仓库被拉黑或者屏蔽导致的

**Comment by gebangfeng** [comment]
有这个可能
https://github.com/DaoCloud/crproxy/pkgs/container/crproxy%2Fcrproxy
你可以使用`ghcr.io/daocloud/crproxy/crproxy:v0.9.0-alpha.3`试试

**Comment by liudonghua123** [comment]
> 有这个可能 https://github.com/DaoCloud/crproxy/pkgs/container/crproxy%2Fcrproxy 你可以使用`ghcr.io/daocloud/crproxy/crproxy:v0.9.0-alpha.3`试试

用这个镜像可以，但最后还是需要输入visa 银行卡号验证，哎

![image](https://github.com/user-attachments/assets/55112319-309c-49e2-a356-665fed5be062)

**Comment by gebangfeng** [comment]
可能免费方案失效了，那你试试`sealos`的部署方案吧

**Comment by liudonghua123** [comment]
> 可能免费方案失效了，那你试试`sealos`的部署方案吧

嗯，是的，我试了虚拟的 [visa](https://cardgenerator.org/) 卡号也不行，国内的 Union Pay 不支持，可以文档中宣告这一种方式已不可用，除非有 visa 信用卡；我之前已经部署的也已经被删了。

[sealos](https://github.com/labring/sealos) 可以详细说明以下么？

**Comment by gebangfeng** [comment]
> > 可能免费方案失效了，那你试试`sealos`的部署方案吧
> 
> 嗯，是的，我试了虚拟的 [visa](https://cardgenerator.org/) 卡号也不行，国内的 Union Pay 不支持，可以文档中宣告这一种方式已不可用，除非有 visa 信用卡；我之前已经部署的也已经被删了。
> 
> [sealos](https://github.com/labring/sealos) 可以详细说明以下么？

https://github.com/kubesre/docker-registry-mirrors/blob/main/dockerproxy/Sealos/README.md
